# DataFrame Exploration

This notebook defines helper functions to load the pre-built dataframes from
`src.data.load_excel_sheets` and then displays several of them to verify that
they look as expected.

In [2]:
import os
print(os.getcwd())

c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\notebooks

In [3]:
# Import Required Modules
import importlib
from typing import Dict
import sys
import pathlib

import pandas as pd

# Ensure workspace root is on path so 'src' and 'config' can be imported
root = pathlib.Path.cwd().parents[0]
if str(root) not in sys.path:
    sys.path.insert(0, str(root))

# Import the loader module
from src.data import load_excel_sheets

# Reload to get the latest version if the module was edited during the session
load_excel_sheets = importlib.reload(load_excel_sheets)

print("✓ Loader module imported successfully from", load_excel_sheets.__file__)

c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDNOK Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDKRW Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDSGD Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDTWD Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDMXN Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDCNH Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDINR Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'BBDXY Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'EMFXDBET Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG2YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG5YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG10YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 3M1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 6M1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 1Y1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'RR2YHUS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'SPX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'FTW5000 Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'INDU Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'MXUS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'BCOM Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'CO1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'XAU Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'FN1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'TZT1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'NG1 COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'HGA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'LMCADS03 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'VIX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'MOVE Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'JPMVG71M Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU2YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU5YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU10YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'RR2YHEA Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GTITL10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GTDEM10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'SXXP Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'JYSST10 BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'NXY Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'SMI Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'RR2YHGB Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'UKX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'MCX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'GTNZD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'GTNZD5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'RR2YHnz Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'NZX20X Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'OMRA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'FSPA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'GTAUD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'GTAUD5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'RR2YHAU Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'AS51 Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'SCOH6 COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'IACA COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'GTCAD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'RR2YHCA Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'SPTSX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'USCRWCAS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK10YR Corp'; those rows will be NaT
  warnings.warn(

✓ Loader module imported successfully from c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py

c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'RR2YHAU Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'AS51 Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'SCOH6 COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'IACA COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'GTCAD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'RR2YHCA Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'SPTSX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'USCRWCAS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'G0078 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'G0078 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'G0078 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'RR2YHNO Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'SEK', column 'GTSEK2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'SEK', column 'GTSEK5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'SEK', column 'GTSEK10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'SEK', column 'G0021 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'SEK', column 'G0021 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'SEK', column 'G0021 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'SEK', column 'OMX Index'; those rows will be NaT
  warnings.warn(

In [4]:
# Define Helper Functions to Load DataFrames

def get_sheet_dataframes(module) -> Dict[str, pd.DataFrame]:
    """Return a dictionary of attribute name to DataFrame found in `module`.

    The loader module exposes variables like ``fx_df`` etc.  We extract those
    by filtering for names that end with "_df" and are DataFrame objects.
    """
    result: Dict[str, pd.DataFrame] = {}
    for name in dir(module):
        if name.endswith("_df"):
            attr = getattr(module, name)
            if isinstance(attr, pd.DataFrame):
                result[name] = attr
    return result


def load_all() -> Dict[str, pd.DataFrame]:
    """Reload the loader module and return all dataframes.
    
    The loader automatically resolves paths from config.py, so no path argument
    is needed here. This function simply triggers a reload and extracts the
    module-level dataframe variables.
    """
    mod = importlib.reload(load_excel_sheets)
    return get_sheet_dataframes(mod)

In [5]:
# Load DataFrames from Python File

frames = load_all()
frames

c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDNOK Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDKRW Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDSGD Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDTWD Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDMXN Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDCNH Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'USDINR Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'BBDXY Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'FX', column 'EMFXDBET Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG2YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG5YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'USGG10YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 3M1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 6M1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'S0042FS 1Y1M BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'RR2YHUS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'SPX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'FTW5000 Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'INDU Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'MXUS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'BCOM Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'CO1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'XAU Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'FN1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'TZT1 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'NG1 COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'HGA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'LMCADS03 Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'VIX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'MOVE Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'USD', column 'JPMVG71M Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU2YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU5YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GECU10YR Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'RR2YHEA Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GTITL10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'GTDEM10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'EUR', column 'SXXP Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'GTJPY10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'G0018 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'JYSST10 BLC Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'JPY', column 'NXY Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'GTCHF10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'G0082 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CHF', column 'SMI Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'GTGBP10YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'RR2YHGB Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'UKX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'GBP', column 'MCX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'GTNZD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'GTNZD5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'G0049 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'RR2YHnz Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'NZX20X Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'OMRA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NZD', column 'FSPA Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'GTAUD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'GTAUD5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'G0001 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'RR2YHAU Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'AS51 Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'SCOH6 COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'AUD', column 'IACA COMB Comdty'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'GTCAD2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 3M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 6M1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'G0007 1Y1M BLC2 Curncy'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'RR2YHCA Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'SPTSX Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'CAD', column 'USCRWCAS Index'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK2YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK5YR Corp'; those rows will be NaT
  warnings.warn(
c:\Users\tilik\Cambridge\Year_1\D200\fx_valuation\fxvaluation_d200_am3483\src\data\load_excel_sheets.py:85: UserWarning: Unable to parse some dates in sheet 'NOK', column 'GTNOK10YR Corp'; those rows will be NaT
  warnings.warn(

{'aud_df':             GTAUD2YR Corp  GTAUD5YR Corp  GTAUD10YR Corp  \
 2000-03-01          6.108          6.515           6.550
 2000-03-02          6.155          6.590           6.665
 2000-03-03          6.115          6.575           6.605
 2000-03-06          6.420          6.760           6.755
 2000-03-07          6.430          6.785           6.685
 ...                   ...            ...             ...
 2026-02-13          4.241          4.388           4.748
 2026-02-16          4.222          4.362           4.709
 2026-02-17          4.186          4.331           4.685
 2026-02-18          4.219          4.368           4.723
 NaT                   NaN            NaN             NaN

             G0001 3M1M BLC2 Curncy  G0001 6M1M BLC2 Curncy  \
 2000-03-01                     NaN                     NaN
 2000-03-02                     NaN                     NaN
 2000-03-03                     NaN                     NaN
 2000-03-06                     NaN                     NaN
 2000-03-07                     NaN                     NaN
 ...                            ...                     ...
 2026-02-13                 4.11403                 4.22824
 2026-02-16                 4.13371                 4.20408
 2026-02-17                 4.10455                 4.17293
 2026-02-18                 4.13220                 4.20384
 NaT                            NaN                     NaN

             G0001 1Y1M BLC2 Curncy  RR2YHAU Index  AS51 Index  \
 2000-03-01                     NaN           3.31    3187.200
 2000-03-02                     NaN           3.36    3219.800
 2000-03-03                     NaN           3.32    3232.600
 2000-03-06                     NaN           3.62    3214.000
 2000-03-07                     NaN           3.63    3232.500
 ...                            ...            ...         ...
 2026-02-13                 4.15834            NaN    8917.612
 2026-02-16                 4.13482            NaN    8937.095
 2026-02-17                 4.10420            NaN    8958.878
 2026-02-18                 4.13459            NaN    9006.984
 NaT                            NaN            NaN         NaN

             SCOH6 COMB Comdty  IACA COMB Comdty
 2000-03-01                NaN               NaN
 2000-03-02                NaN               NaN
 2000-03-03                NaN               NaN
 2000-03-06                NaN               NaN
 2000-03-07                NaN               NaN
 ...                       ...               ...
 2026-02-13              96.75             222.0
 2026-02-16              96.65             222.0
 2026-02-17              96.19             221.0
 2026-02-18              95.72             221.0
 NaT                       NaN               NaN

 [6776 rows x 10 columns],
 'cad_df':             GTCAD2YR Corp  GTCAD5YR Corp  GTCAD10YR Corp  \
 2000-03-01          5.976          6.171           6.098
 2000-03-02          5.997          6.185           6.110
 2000-03-03          5.953          6.143           6.086
 2000-03-06          6.004          6.205           6.135
 2000-03-07          5.959          6.173           6.116
 ...                   ...            ...             ...
 2026-02-13          2.473          2.787           3.254
 2026-02-16          2.473          2.787           3.254
 2026-02-17          2.450          2.763           3.226
 2026-02-18          2.447          2.769           3.231
 NaT                   NaN            NaN             NaN

             G0007 3M1M BLC2 Curncy  G0007 6M1M BLC2 Curncy  \
 2000-03-01                 5.87310                 5.90442
 2000-03-02                 5.89260                 5.92402
 2000-03-03                 5.85179                 5.88394
 2000-03-06                 5.89864                 5.93105
 2000-03-07                 5.85504                 5.88863
 ...                            ...                     ...
 2026-02-13                 2.24850                 2.35772
 2026-02-16                 2.24836                 2.35764
 2026-02-17                 2.23905                 2.32804
 2026-02-18                 2.23454                 2.33513
 NaT                            NaN                     NaN

             G0007 1Y1M BLC2 Curncy  RR2YHCA Index  SPTSX Index  USCRWCAS Index
 2000-03-01                 5.87263           2.93      9411.58             NaN
 2000-03-02                 5.89212           2.95      9516.06             NaN
 2000-03-03                 5.85226           2.91      9462.90             NaN
 2000-03-06                 5.89911           2.96      9580.87             NaN
 2000-03-07                 5.85645           2.91      9425.48             NaN
 ...                            ...            ...          ...             ...
 2026-02-13                 2.60907            NaN     33073.71           47.06
 2026-02-16                 2.58532            NaN          NaN             NaN
 2026-02-17                 2.58261            NaN     32896.55           46.57
 2026-02-18                 2.57395            NaN     33258.45             NaN
 NaT                            NaN            NaN          NaN             NaN

 [6777 rows x 9 columns],
 'chf_df':             GTCHF2YR Corp  GTCHF5YR Corp  GTCHF10YR Corp  \
 2000-03-01            NaN            NaN             NaN
 2000-03-02            NaN            NaN             NaN
 2000-03-03            NaN            NaN             NaN
 2000-03-06            NaN            NaN             NaN
 2000-03-07            NaN            NaN             NaN
 ...                   ...            ...             ...
 2026-02-13         -0.150          0.072           0.243
 2026-02-16         -0.154          0.063           0.233
 2026-02-17         -0.164          0.037           0.209
 2026-02-18         -0.159          0.042           0.215
 NaT                   NaN            NaN             NaN

             G0082 3M1M BLC2 Curncy  G0082 6M1M BLC2 Curncy  \
 2000-03-01                     NaN                     NaN
 2000-03-02                     NaN                     NaN
 2000-03-03                     NaN                     NaN
 2000-03-06                     NaN                     NaN
 2000-03-07                     NaN                     NaN
 ...                            ...                     ...
 2026-02-13                -0.10970                -0.19901
 2026-02-16                -0.11200                -0.20068
 2026-02-17                -0.10752                -0.20519
 2026-02-18                -0.10080                -0.19978
 NaT                            NaN                     NaN

             G0082 1Y1M BLC2 Curncy  RR2YHCH Index  SMI Index
 2000-03-01                     NaN           1.78    6959.10
 2000-03-02                     NaN           1.80    7052.40
 2000-03-03                     NaN           1.79    7025.30
 2000-03-06                     NaN           1.80    7087.70
 2000-03-07                     NaN           1.76    7050.20
 ...                            ...            ...        ...
 2026-02-13                -0.17994            NaN   13600.67
 2026-02-16                -0.18126            NaN   13656.00
 2026-02-17                -0.18534            NaN   13752.84
 2026-02-18                -0.18045            NaN   13815.76
 NaT                            NaN            NaN        NaN

 [6701 rows x 8 columns],
 'eur_df':             GECU2YR Index  GECU5YR Index  GECU10YR Index  \
 2000-03-01          4.533          5.077           5.486
 2000-03-02          4.573          5.121           5.527
 2000-03-03          4.560          5.073           5.461
 2000-03-06          4.564          5.071           5.454
 2000-03-07          4.564          5.044           5.432
 ...                   ...            ...             ...
 2026-02-13          2.036          2.337           2.755
 2026-02-16          2.041          2.339           2.754
 2026-02-17          2.036          2.328           2.738
 2026-02-18          2.053          2.338           2.743
 NaT                   NaN            NaN             NaN

             G0013 3M1M BLC2 Curncy  G0013 6M1M BLC2 Curncy  \
 2000-03-01                 3.77314                 4.52579
 2000-03-02                 3.76704                 4.59427
 2000-03-03                 3.77476                 4.61274
 2000-03-06                 3.90900                 4.63391
 2000-03-07                 3.85761                 4.66354
 ...                            ...                     ...
 2026-02-13                 2.06517                 2.04708
 2026-02-16                 2.06495                 2.05093
 2026-02-17                 2.06853                 2.03224
 2026-02-18                 2.07071                 2.04070
 NaT                            NaN                     NaN

             G0013 1Y1M BLC2 Curncy  RR2YHEA Index  GTITL10YR Corp  \
 2000-03-01                 4.84622           2.53           5.753
 2000-03-02                 4.89167           2.57           5.790
 2000-03-03                 4.85085           2.56           5.722
 2000-03-06                 4.84470           2.56           5.720
 2000-03-07                 4.83139           2.56           5.705
 ...                            ...            ...             ...
 2026-02-13                 1.97800            NaN           3.363
 2026-02-16                 1.98280            NaN           3.366
 2026-02-17                 1.97640            NaN           3.349
 2026-02-18                 1.99913            NaN           3.343
 NaT                            NaN            NaN             NaN

             GTDEM10YR Corp  SXXP Index
 2000-03-01           5.486      391.03
 2000-03-02           5.527      398.98
 2000-03-03           5.461      402.57
 2000-03-06           5.454      405.50
 2000-03-07           5.432      402.62
 ...                    ...         ...
 2026-02-13           2.754      617.70
 2026-02-16           2.753      618.52
 2026-02-17           2.737      621.29
 2026-02-18           2.742      628.66
 NaT                    NaN         NaN

 [6777 rows x 10 columns],
 'fx_df':             EURUSD Curncy  GBPUSD Curncy  AUDUSD Curncy  NZDUSD Curncy  \
 2000-03-01         0.9727         1.5854         0.6057         0.4872
 2000-03-02         0.9656         1.5766         0.6063         0.4873
 2000-03-03         0.9586         1.5778         0.6084         0.4884
 2000-03-06         0.9586         1.5749         0.6019         0.4830
 2000-03-07         0.9584         1.5804         0.6051         0.4845
 ...                   ...            ...            ...            ...
 2026-02-13         1.1868         1.3651         0.7073         0.6039
 2026-02-16         1.1851         1.3629         0.7072         0.6033
 2026-02-17         1.1855         1.3568         0.7086         0.6049
 2026-02-18         1.1823         1.3547         0.7069         0.5991
 NaT                   NaN            NaN            NaN            NaN

             USDJPY Curncy  USDCAD Curncy  USDNOK Curncy  USDSEK Curncy  \
 2000-03-01         107.28         1.4497         8.2904         8.6590
 2000-03-02         107.74         1.4570         8.3528         8.7761
 2000-03-03         107.90         1.4504         8.4157         8.7985
 2000-03-06         107.54         1.4534         8.4259         8.7910
 2000-03-07         106.12         1.4553         8.4171         8.7779
 ...                   ...            ...            ...            ...
 2026-02-13         152.70         1.3617         9.5102         8.9225
 2026-02-16         153.47         1.3636         9.5078         8.9474
 2026-02-17         153.31         1.3636         9.5324         8.9684
 2026-02-18         154.34         1.3666         9.4896         8.9917
 NaT                   NaN            NaN            NaN            NaN

             USDKRW Curncy  USDSGD Curncy  USDTWD Curncy  USDMXN Curncy  \
 2000-03-01        1128.00         1.7158         30.736         9.3515
 2000-03-02        1119.75         1.7215         30.700         9.3175
 2000-03-03        1124.43         1.7250         30.745         9.3090
 2000-03-06        1123.43         1.7252         30.768         9.3248
 2000-03-07        1122.93         1.7175         30.700         9.2675
 ...                   ...            ...            ...            ...
 2026-02-13        1444.10         1.2629         31.511        17.1701
 2026-02-16            NaN         1.2626            NaN        17.1683
 2026-02-17            NaN         1.2631            NaN        17.1283
 2026-02-18            NaN         1.2653            NaN        17.1274
 NaT                   NaN            NaN            NaN            NaN

             USDCNH Curncy  USDINR Curncy  BBDXY Curncy  EMFXDBET Index  \
 2000-03-01            NaN        43.6300           NaN           99.75
 2000-03-02            NaN        43.6250           NaN           99.63
 2000-03-03            NaN        43.6050           NaN           99.55
 2000-03-06            NaN        43.6000           NaN           99.50
 2000-03-07            NaN        43.6000           NaN           99.53
 ...                   ...            ...           ...             ...
 2026-02-13         6.9012        90.6400       1181.35          213.34
 2026-02-16         6.8844        90.6537       1182.95             NaN
 2026-02-17         6.8852        90.6850       1183.30             NaN
 2026-02-18         6.8867        90.6788       1185.77             NaN
 NaT                   NaN            NaN           NaN             NaN

             CTTWBUSA Index
 2000-03-01        102.1843
 2000-03-02        102.0699
 2000-03-03        102.0664
 2000-03-06        102.0657
 2000-03-07        102.0595
 ...                    ...
 2026-02-13        103.3611
 2026-02-16        103.1725
 2026-02-17        103.2271
 2026-02-18        103.2615
 NaT                    NaN

 [6777 rows x 17 columns],
 'gbp_df':             GTGBP2YR Corp  GTGBP5YR Corp  GTGBP10YR Corp  \
 2000-03-01         6.3631         6.0308          5.4221
 2000-03-02         6.3706         6.0546          5.4456
 2000-03-03         6.3467         6.0084          5.3690
 2000-03-06         6.3103         5.9673          5.3124
 2000-03-07         6.2981         5.9524          5.2839
 ...                   ...            ...             ...
 2026-02-13         3.5850         3.8240          4.4151
 2026-02-16         3.5783         3.8064          4.3988
 2026-02-17         3.5789         3.7957          4.3752
 2026-02-18         3.5745         3.7979          4.3730
 NaT                   NaN            NaN             NaN

             G0022 3M1M BLC2 Curncy  G0022 6M1M BLC2 Curncy  \
 2000-03-01                 6.59302                 6.29238
 2000-03-02                 6.64344                 6.30184
 2000-03-03                 6.54286                 6.28544
 2000-03-06                 6.55058                 6.26431
 2000-03-07                 6.59800                 6.25121
 ...                            ...                     ...
 2026-02-13                 3.61427                 3.52833
 2026-02-16                 3.57519                 3.53359
 2026-02-17                 3.56661                 3.54478
 2026-02-18                 3.56012                 3.53320
 NaT                            NaN                     NaN

             G0022 1Y1M BLC2 Curncy  RR2YHGB Index  UKX Index  MCX Index
 2000-03-01                 6.30366           5.76    6364.90    6616.60
 2000-03-02                 6.30609           5.77    6432.10    6676.80
 2000-03-03                 6.28109           5.75    6487.50    6776.60
 2000-03-06                 6.22957           5.71    6567.80    6838.90
 2000-03-07                 6.20989           5.70    6466.50    6789.30
 ...                            ...            ...        ...        ...
 2026-02-13                 3.46366            NaN   10446.35   23427.27
 2026-02-16                 3.46084            NaN   10473.69   23375.47
 2026-02-17                 3.46081            NaN   10556.17   23555.82
 2026-02-18                 3.48184            NaN   10709.65   23694.50
 NaT                            NaN            NaN        NaN        NaN

 [6777 rows x 9 columns],
 'jpy_df':             GTJPY2YR Corp  GTJPY5YR Corp  GTJPY10YR Corp  \
 2000-03-01          0.378          1.130           1.831
 2000-03-02          0.383          1.111           1.789
 2000-03-03          0.406          1.127           1.799
 2000-03-06          0.407          1.117           1.774
 2000-03-07          0.423          1.137           1.792
 ...                   ...            ...             ...
 2026-02-13          1.283          1.681           2.216
 2026-02-16          1.263          1.662           2.204
 2026-02-17          1.226          1.614           2.126
 2026-02-18          1.235          1.620           2.137
 NaT                   NaN            NaN             NaN

             G0018 3M1M BLC2 Curncy  G0018 6M1M BLC2 Curncy  \
 2000-03-01                     NaN                     NaN
 2000-03-02                     NaN                     NaN
 2000-03-03                     NaN                     NaN
 2000-03-06                     NaN                     NaN
 2000-03-07                     NaN                     NaN
 ...                            ...                     ...
 2026-02-13                 0.98938                 1.18132
 2026-02-16                 1.03268                 1.14376
 2026-02-17                 1.02675                 1.10992
 2026-02-18                 1.01643                 1.12153
 NaT                            NaN                     NaN

             G0018 1Y1M BLC2 Curncy  RR2YHJP Index  JYSST10 BLC Curncy  \
 2000-03-01                     NaN           0.88                 NaN
 2000-03-02                     NaN           0.89                 NaN
 2000-03-03                     NaN           0.91                 NaN
 2000-03-06                     NaN           0.90                 NaN
 2000-03-07                     NaN           0.93                 NaN
 ...                            ...            ...                 ...
 2026-02-13                 1.53385            NaN            -23.5001
 2026-02-16                 1.50473            NaN            -22.7500
 2026-02-17                 1.45027            NaN            -20.2000
 2026-02-18                 1.46321            NaN            -19.4000
 NaT                            NaN            NaN                 NaN

             NXY Index
 2000-03-01       10.3
 2000-03-02       10.3
 2000-03-03       10.3
 2000-03-06       10.3
 2000-03-07       10.3
 ...               ...
 2026-02-13        NaN
 2026-02-16        NaN
 2026-02-17        NaN
 2026-02-18        NaN
 NaT               NaN

 [6773 rows x 9 columns],
 'nok_df':             GTNOK2YR Corp  GTNOK5YR Corp  GTNOK10YR Corp  \
 2000-03-01            NaN            NaN             NaN
 2000-03-02            NaN            NaN             NaN
 2000-03-03            NaN            NaN             NaN
 2000-03-06            NaN            NaN             NaN
 2000-03-07            NaN            NaN             NaN
 ...                   ...            ...             ...
 2026-02-13          4.078          4.119           4.255
 2026-02-16          4.061          4.111           4.246
 2026-02-17          3.992          4.061           4.192
 2026-02-18          3.987          4.062           4.209
 NaT                   NaN            NaN             NaN

             G0078 3M1M BLC2 Curncy  G0078 6M1M BLC2 Curncy  \
 2000-03-01                     NaN                     NaN
 2000-03-02                     NaN                     NaN
 2000-03-03                     NaN                     NaN
 2000-03-06                     NaN                     NaN

In [6]:
# Verify Loaded DataFrames

for name, df in frames.items():
    print(f"{name}: {df.shape}")
    display(df.head())

aud_df: (6776, 10)

,GTAUD2YR Corp,GTAUD5YR Corp,GTAUD10YR Corp,G0001 3M1M BLC2 Curncy,G0001 6M1M BLC2 Curncy,G0001 1Y1M BLC2 Curncy,RR2YHAU Index,AS51 Index,SCOH6 COMB Comdty,IACA COMB Comdty
2000-03-01,6.108,6.515,6.550,NaN,NaN,NaN,3.31,3187.2,NaN,NaN
2000-03-02,6.155,6.590,6.665,NaN,NaN,NaN,3.36,3219.8,NaN,NaN
2000-03-03,6.115,6.575,6.605,NaN,NaN,NaN,3.32,3232.6,NaN,NaN
2000-03-06,6.420,6.760,6.755,NaN,NaN,NaN,3.62,3214.0,NaN,NaN
2000-03-07,6.430,6.785,6.685,NaN,NaN,NaN,3.63,3232.5,NaN,NaN

cad_df: (6777, 9)

,GTCAD2YR Corp,GTCAD5YR Corp,GTCAD10YR Corp,G0007 3M1M BLC2 Curncy,G0007 6M1M BLC2 Curncy,G0007 1Y1M BLC2 Curncy,RR2YHCA Index,SPTSX Index,USCRWCAS Index
2000-03-01,5.976,6.171,6.098,5.87310,5.90442,5.87263,2.93,9411.58,NaN
2000-03-02,5.997,6.185,6.110,5.89260,5.92402,5.89212,2.95,9516.06,NaN
2000-03-03,5.953,6.143,6.086,5.85179,5.88394,5.85226,2.91,9462.90,NaN
2000-03-06,6.004,6.205,6.135,5.89864,5.93105,5.89911,2.96,9580.87,NaN
2000-03-07,5.959,6.173,6.116,5.85504,5.88863,5.85645,2.91,9425.48,NaN

chf_df: (6701, 8)

,GTCHF2YR Corp,GTCHF5YR Corp,GTCHF10YR Corp,G0082 3M1M BLC2 Curncy,G0082 6M1M BLC2 Curncy,G0082 1Y1M BLC2 Curncy,RR2YHCH Index,SMI Index
2000-03-01,NaN,NaN,NaN,NaN,NaN,NaN,1.78,6959.1
2000-03-02,NaN,NaN,NaN,NaN,NaN,NaN,1.80,7052.4
2000-03-03,NaN,NaN,NaN,NaN,NaN,NaN,1.79,7025.3
2000-03-06,NaN,NaN,NaN,NaN,NaN,NaN,1.80,7087.7
2000-03-07,NaN,NaN,NaN,NaN,NaN,NaN,1.76,7050.2

eur_df: (6777, 10)

,GECU2YR Index,GECU5YR Index,GECU10YR Index,G0013 3M1M BLC2 Curncy,G0013 6M1M BLC2 Curncy,G0013 1Y1M BLC2 Curncy,RR2YHEA Index,GTITL10YR Corp,GTDEM10YR Corp,SXXP Index
2000-03-01,4.533,5.077,5.486,3.77314,4.52579,4.84622,2.53,5.753,5.486,391.03
2000-03-02,4.573,5.121,5.527,3.76704,4.59427,4.89167,2.57,5.790,5.527,398.98
2000-03-03,4.560,5.073,5.461,3.77476,4.61274,4.85085,2.56,5.722,5.461,402.57
2000-03-06,4.564,5.071,5.454,3.90900,4.63391,4.84470,2.56,5.720,5.454,405.50
2000-03-07,4.564,5.044,5.432,3.85761,4.66354,4.83139,2.56,5.705,5.432,402.62

fx_df: (6777, 17)

,EURUSD Curncy,GBPUSD Curncy,AUDUSD Curncy,NZDUSD Curncy,USDJPY Curncy,USDCAD Curncy,USDNOK Curncy,USDSEK Curncy,USDKRW Curncy,USDSGD Curncy,USDTWD Curncy,USDMXN Curncy,USDCNH Curncy,USDINR Curncy,BBDXY Curncy,EMFXDBET Index,CTTWBUSA Index
2000-03-01,0.9727,1.5854,0.6057,0.4872,107.28,1.4497,8.2904,8.6590,1128.00,1.7158,30.736,9.3515,NaN,43.630,NaN,99.75,102.1843
2000-03-02,0.9656,1.5766,0.6063,0.4873,107.74,1.4570,8.3528,8.7761,1119.75,1.7215,30.700,9.3175,NaN,43.625,NaN,99.63,102.0699
2000-03-03,0.9586,1.5778,0.6084,0.4884,107.90,1.4504,8.4157,8.7985,1124.43,1.7250,30.745,9.3090,NaN,43.605,NaN,99.55,102.0664
2000-03-06,0.9586,1.5749,0.6019,0.4830,107.54,1.4534,8.4259,8.7910,1123.43,1.7252,30.768,9.3248,NaN,43.600,NaN,99.50,102.0657
2000-03-07,0.9584,1.5804,0.6051,0.4845,106.12,1.4553,8.4171,8.7779,1122.93,1.7175,30.700,9.2675,NaN,43.600,NaN,99.53,102.0595

gbp_df: (6777, 9)

,GTGBP2YR Corp,GTGBP5YR Corp,GTGBP10YR Corp,G0022 3M1M BLC2 Curncy,G0022 6M1M BLC2 Curncy,G0022 1Y1M BLC2 Curncy,RR2YHGB Index,UKX Index,MCX Index
2000-03-01,6.3631,6.0308,5.4221,6.59302,6.29238,6.30366,5.76,6364.9,6616.6
2000-03-02,6.3706,6.0546,5.4456,6.64344,6.30184,6.30609,5.77,6432.1,6676.8
2000-03-03,6.3467,6.0084,5.3690,6.54286,6.28544,6.28109,5.75,6487.5,6776.6
2000-03-06,6.3103,5.9673,5.3124,6.55058,6.26431,6.22957,5.71,6567.8,6838.9
2000-03-07,6.2981,5.9524,5.2839,6.59800,6.25121,6.20989,5.70,6466.5,6789.3

jpy_df: (6773, 9)

,GTJPY2YR Corp,GTJPY5YR Corp,GTJPY10YR Corp,G0018 3M1M BLC2 Curncy,G0018 6M1M BLC2 Curncy,G0018 1Y1M BLC2 Curncy,RR2YHJP Index,JYSST10 BLC Curncy,NXY Index
2000-03-01,0.378,1.130,1.831,NaN,NaN,NaN,0.88,NaN,10.3
2000-03-02,0.383,1.111,1.789,NaN,NaN,NaN,0.89,NaN,10.3
2000-03-03,0.406,1.127,1.799,NaN,NaN,NaN,0.91,NaN,10.3
2000-03-06,0.407,1.117,1.774,NaN,NaN,NaN,0.90,NaN,10.3
2000-03-07,0.423,1.137,1.792,NaN,NaN,NaN,0.93,NaN,10.3

nok_df: (6717, 8)

,GTNOK2YR Corp,GTNOK5YR Corp,GTNOK10YR Corp,G0078 3M1M BLC2 Curncy,G0078 6M1M BLC2 Curncy,G0078 1Y1M BLC2 Curncy,RR2YHNO Index,OBX Index
2000-03-01,NaN,NaN,NaN,NaN,NaN,NaN,3.64,150.775
2000-03-02,NaN,NaN,NaN,NaN,NaN,NaN,3.65,150.816
2000-03-03,NaN,NaN,NaN,NaN,NaN,NaN,3.65,151.840
2000-03-06,NaN,NaN,NaN,NaN,NaN,NaN,3.66,152.813
2000-03-07,NaN,NaN,NaN,NaN,NaN,NaN,3.63,157.516

nzd_df: (6720, 10)

,GTNZD2YR Corp,GTNZD5YR Corp,GTNZD10YR Corp,G0049 3M1M BLC2 Curncy,G0049 6M1M BLC2 Curncy,G0049 1Y1M BLC2 Curncy,RR2YHnz Index,NZX20X Index,OMRA Comdty,FSPA Comdty
2000-03-01,7.015,NaN,7.095,NaN,NaN,NaN,5.50,NaN,NaN,NaN
2000-03-02,7.030,NaN,7.135,NaN,NaN,NaN,5.52,NaN,NaN,NaN
2000-03-03,7.012,NaN,7.182,NaN,NaN,NaN,5.49,NaN,NaN,NaN
2000-03-06,7.040,NaN,7.220,NaN,NaN,NaN,5.52,NaN,NaN,NaN
2000-03-07,7.040,NaN,7.180,NaN,NaN,NaN,5.54,NaN,NaN,NaN

sek_df: (6754, 8)

,GTSEK2YR Corp,GTSEK5YR Corp,GTSEK10YR Corp,G0021 3M1M BLC2 Curncy,G0021 6M1M BLC2 Curncy,G0021 1Y1M BLC2 Curncy,RR2YHSE Index,OMX Index
2000-03-01,NaN,NaN,NaN,NaN,NaN,NaN,4.35,1463.75
2000-03-02,NaN,NaN,NaN,NaN,NaN,NaN,4.38,1515.62
2000-03-03,NaN,NaN,NaN,NaN,NaN,NaN,4.37,1530.02
2000-03-06,NaN,NaN,NaN,NaN,NaN,NaN,4.38,1537.33
2000-03-07,NaN,NaN,NaN,NaN,NaN,NaN,4.38,1539.00

usd_df: (6777, 25)

,USGG2YR Index,USGG5YR Index,USGG10YR Index,S0042FS 3M1M BLC Curncy,S0042FS 6M1M BLC Curncy,S0042FS 1Y1M BLC Curncy,RR2YHUS Index,SPX Index,FTW5000 Index,INDU Index,...,CO1 Comdty,XAU Curncy,FN1 Comdty,TZT1 Comdty,NG1 COMB Comdty,HGA Comdty,LMCADS03 Comdty,VIX Index,MOVE Index,JPMVG71M Index
2000-03-01,6.504,6.571,6.386,NaN,NaN,NaN,2.74186,1379.19,13950.2895,10137.93,...,29.06,289.75,11.99,NaN,2.815,NaN,1773.0,21.64,104.14,NaN
2000-03-02,6.513,6.583,6.384,NaN,NaN,NaN,2.75086,1381.76,13940.8971,10164.92,...,29.22,288.50,11.72,NaN,2.783,NaN,1752.0,21.06,99.68,NaN
2000-03-03,6.495,6.593,6.388,NaN,NaN,NaN,2.73286,1409.17,14262.9495,10367.20,...,28.99,288.80,11.65,NaN,2.825,NaN,1761.0,19.21,94.85,NaN
2000-03-06,6.529,6.625,6.411,NaN,NaN,NaN,2.76686,1391.28,14141.8140,10170.51,...,29.63,287.63,11.67,NaN,2.850,NaN,1768.0,21.50,92.06,NaN
2000-03-07,6.486,6.569,6.373,NaN,NaN,NaN,2.72386,1355.62,13837.3736,9796.04,...,31.90,293.25,11.69,NaN,2.799,NaN,1749.0,24.31,97.13,NaN

In [18]:
  # Template: Drop Columns from DataFrames

def drop_columns(df: pd.DataFrame, columns_to_drop: list[str]) -> pd.DataFrame:
    """Drop specified columns from a dataframe.
    
    Parameters
    ----------
    df : pd.DataFrame
        The dataframe to filter.
    columns_to_drop : list[str]
        List of column names to remove.
    
    Returns
    -------
    pd.DataFrame
         dataframe with specified columns removed.
        
    Raises
    ------
    ValueError
        If any specified column doesn't exist in the dataframe.
    """
    missing = [col for col in columns_to_drop if col not in df.columns]
    if missing:
        raise ValueError(f"Columns not found in dataframe: {missing}")
    
    return df.drop(columns=columns_to_drop)


# Example: Drop columns from sek_df
sek_df = drop_columns(
    frames["sek_df"],
    columns_to_drop=[
        "G0021 3M1M BLC2 Curncy",
        "G0021 6M1M BLC2 Curncy",
        "G0021 1Y1M BLC2 Curncy"
    ]
)

print(f"\nRemaining columns in sek_df:\n{list(sek_df.columns)}")
print(f"Original sek_df shape: {frames['sek_df'].shape}")
print(f" sek_df shape: {sek_df.shape}")



# Example: Drop columns from nok_df
nok_df = drop_columns(
    frames["nok_df"],
    columns_to_drop=[
        "G0078 3M1M BLC2 Curncy",
        "G0078 6M1M BLC2 Curncy",
        "G0078 1Y1M BLC2 Curncy"
    ]
)

print(f"\nRemaining columns in nok_df:\n{list(nok_df.columns)}")
print(f"Original nok_df shape: {frames['nok_df'].shape}")
print(f" nok_df shape: {nok_df.shape}")

# Example: Drop columns from aud_df
aud_df = drop_columns(
    frames["aud_df"],
    columns_to_drop=[
        "G0001 3M1M BLC2 Curncy",
        "G0001 6M1M BLC2 Curncy",
        "G0001 1Y1M BLC2 Curncy"
    ]
)

print(f"\nRemaining columns in aud_df:\n{list(aud_df.columns)}")
print(f"Original aud_df shape: {frames['aud_df'].shape}")
print(f" aud_df shape: {aud_df.shape}")


# Example: Drop columns from nzd_df
nzd_df = drop_columns(
    frames["nzd_df"],
    columns_to_drop=[
        "G0049 3M1M BLC2 Curncy",
        "G0049 6M1M BLC2 Curncy",
        "G0049 1Y1M BLC2 Curncy"
    ]
)

print(f"\nRemaining columns in nzd_df:\n{list(nzd_df.columns)}")
print(f"Original nzd_df shape: {frames['nzd_df'].shape}")
print(f" nzd_df shape: {nzd_df.shape}")


# Example: Drop columns from chf_df
chf_df = drop_columns(
    frames["chf_df"],
    columns_to_drop=[
        "G0082 3M1M BLC2 Curncy",
        "G0082 6M1M BLC2 Curncy",
        "G0082 1Y1M BLC2 Curncy"
    ]
)

print(f"\nRemaining columns in chf_df:\n{list(chf_df.columns)}")
print(f"Original chf_df shape: {frames['chf_df'].shape}")
print(f" chf_df shape: {chf_df.shape}")


# Example: Drop columns from jpy_df
jpy_df = drop_columns(
    frames["jpy_df"],
    columns_to_drop=[
        "G0018 3M1M BLC2 Curncy",
        "G0018 6M1M BLC2 Curncy",
        "G0018 1Y1M BLC2 Curncy"
    ]
)

print(f"\nRemaining columns in jpy_df:\n{list(jpy_df.columns)}")
print(f"Original jpy_df shape: {frames['jpy_df'].shape}")
print(f" jpy_df shape: {jpy_df.shape}")


fx_df = frames["fx_df"]
print(f"\nColumns in fx_df:\n{list(fx_df.columns)}")
print(f" jpy_df shape: {fx_df.shape}")

usd_df = frames["usd_df"]
print(f"\nColumns in usd_df:\n{list(usd_df.columns)}")
print(f" usd_df shape: {usd_df.shape}")

eur_df = frames["eur_df"]
print(f"\nColumns in eur_df:\n{list(eur_df.columns)}")
print(f" eur_df shape: {eur_df.shape}")
gbp_df = frames["gbp_df"]
print(f"\nColumns in gbp_df:\n{list(gbp_df.columns)}")
print(f" gbp_df shape: {gbp_df.shape}")

cad_df = frames["cad_df"]
print(f"\nColumns in cad_df:\n{list(cad_df.columns)}")
print(f" cad_df shape: {cad_df.shape}")

Remaining columns in sek_df:
['GTSEK2YR Corp', 'GTSEK5YR Corp', 'GTSEK10YR Corp', 'RR2YHSE Index', 'OMX Index']
Original sek_df shape: (6754, 8)
 sek_df shape: (6754, 5)

Remaining columns in nok_df:
['GTNOK2YR Corp', 'GTNOK5YR Corp', 'GTNOK10YR Corp', 'RR2YHNO Index', 'OBX Index']
Original nok_df shape: (6717, 8)
 nok_df shape: (6717, 5)

Remaining columns in aud_df:
['GTAUD2YR Corp', 'GTAUD5YR Corp', 'GTAUD10YR Corp', 'RR2YHAU Index', 'AS51 Index', 'SCOH6 COMB Comdty', 'IACA COMB Comdty']
Original aud_df shape: (6776, 10)
 aud_df shape: (6776, 7)

Remaining columns in nzd_df:
['GTNZD2YR Corp', 'GTNZD5YR Corp', 'GTNZD10YR Corp', 'RR2YHnz Index', 'NZX20X Index', 'OMRA Comdty', 'FSPA Comdty']
Original nzd_df shape: (6720, 10)
 nzd_df shape: (6720, 7)

Remaining columns in chf_df:
['GTCHF2YR Corp', 'GTCHF5YR Corp', 'GTCHF10YR Corp', 'RR2YHCH Index', 'SMI Index']
Original chf_df shape: (6701, 8)
 chf_df shape: (6701, 5)

Remaining columns in jpy_df:
['GTJPY2YR Corp', 'GTJPY5YR Corp', 'GTJPY10YR Corp', 'RR2YHJP Index', 'JYSST10 BLC Curncy', 'NXY Index']
Original jpy_df shape: (6773, 9)
 jpy_df shape: (6773, 6)

Columns in fx_df:
['EURUSD Curncy', 'GBPUSD Curncy', 'AUDUSD Curncy', 'NZDUSD Curncy', 'USDJPY Curncy', 'USDCAD Curncy', 'USDNOK Curncy', 'USDSEK Curncy', 'USDKRW Curncy', 'USDSGD Curncy', 'USDTWD Curncy', 'USDMXN Curncy', 'USDCNH Curncy', 'USDINR Curncy', 'BBDXY Curncy', 'EMFXDBET Index', 'CTTWBUSA Index']
 jpy_df shape: (6777, 17)

Columns in usd_df:
['USGG2YR Index', 'USGG5YR Index', 'USGG10YR Index', 'S0042FS 3M1M BLC Curncy', 'S0042FS 6M1M BLC Curncy', 'S0042FS 1Y1M BLC Curncy', 'RR2YHUS Index', 'SPX Index', 'FTW5000 Index', 'INDU Index', 'MXUS Index', 'MXWO Index', 'MXWOU Index', 'MXEF Index', 'BCOM Index', 'CO1 Comdty', 'XAU Curncy', 'FN1 Comdty', 'TZT1 Comdty', 'NG1 COMB Comdty', 'HGA Comdty', 'LMCADS03 Comdty', 'VIX Index', 'MOVE Index', 'JPMVG71M Index']
 usd_df shape: (6777, 25)

Columns in eur_df:
['GECU2YR Index', 'GECU5YR Index', 'GECU10YR Index', 'G0013 3M1M BLC2 Curncy', 'G0013 6M1M BLC2 Curncy', 'G0013 1Y1M BLC2 Curncy', 'RR2YHEA Index', 'GTITL10YR Corp', 'GTDEM10YR Corp', 'SXXP Index']
 eur_df shape: (6777, 10)

Columns in gbp_df:
['GTGBP2YR Corp', 'GTGBP5YR Corp', 'GTGBP10YR Corp', 'G0022 3M1M BLC2 Curncy', 'G0022 6M1M BLC2 Curncy', 'G0022 1Y1M BLC2 Curncy', 'RR2YHGB Index', 'UKX Index', 'MCX Index']
 gbp_df shape: (6777, 9)

Columns in cad_df:
['GTCAD2YR Corp', 'GTCAD5YR Corp', 'GTCAD10YR Corp', 'G0007 3M1M BLC2 Curncy', 'G0007 6M1M BLC2 Curncy', 'G0007 1Y1M BLC2 Curncy', 'RR2YHCA Index', 'SPTSX Index', 'USCRWCAS Index']
 cad_df shape: (6777, 9)

In [14]:
fx_df = frames["fx_df"]
print(fx_df)

            EURUSD Curncy  GBPUSD Curncy  AUDUSD Curncy  NZDUSD Curncy  \
2000-03-01         0.9727         1.5854         0.6057         0.4872
2000-03-02         0.9656         1.5766         0.6063         0.4873
2000-03-03         0.9586         1.5778         0.6084         0.4884
2000-03-06         0.9586         1.5749         0.6019         0.4830
2000-03-07         0.9584         1.5804         0.6051         0.4845
...                   ...            ...            ...            ...
2026-02-13         1.1868         1.3651         0.7073         0.6039
2026-02-16         1.1851         1.3629         0.7072         0.6033
2026-02-17         1.1855         1.3568         0.7086         0.6049
2026-02-18         1.1823         1.3547         0.7069         0.5991
NaT                   NaN            NaN            NaN            NaN

            USDJPY Curncy  USDCAD Curncy  USDNOK Curncy  USDSEK Curncy  \
2000-03-01         107.28         1.4497         8.2904         8.6590
2000-03-02         107.74         1.4570         8.3528         8.7761
2000-03-03         107.90         1.4504         8.4157         8.7985
2000-03-06         107.54         1.4534         8.4259         8.7910
2000-03-07         106.12         1.4553         8.4171         8.7779
...                   ...            ...            ...            ...
2026-02-13         152.70         1.3617         9.5102         8.9225
2026-02-16         153.47         1.3636         9.5078         8.9474
2026-02-17         153.31         1.3636         9.5324         8.9684
2026-02-18         154.34         1.3666         9.4896         8.9917
NaT                   NaN            NaN            NaN            NaN

            USDKRW Curncy  USDSGD Curncy  USDTWD Curncy  USDMXN Curncy  \
2000-03-01        1128.00         1.7158         30.736         9.3515
2000-03-02        1119.75         1.7215         30.700         9.3175
2000-03-03        1124.43         1.7250         30.745         9.3090
2000-03-06        1123.43         1.7252         30.768         9.3248
2000-03-07        1122.93         1.7175         30.700         9.2675
...                   ...            ...            ...            ...
2026-02-13        1444.10         1.2629         31.511        17.1701
2026-02-16            NaN         1.2626            NaN        17.1683
2026-02-17            NaN         1.2631            NaN        17.1283
2026-02-18            NaN         1.2653            NaN        17.1274
NaT                   NaN            NaN            NaN            NaN

            USDCNH Curncy  USDINR Curncy  BBDXY Curncy  EMFXDBET Index  \
2000-03-01            NaN        43.6300           NaN           99.75
2000-03-02            NaN        43.6250           NaN           99.63
2000-03-03            NaN        43.6050           NaN           99.55
2000-03-06            NaN        43.6000           NaN           99.50
2000-03-07            NaN        43.6000           NaN           99.53
...                   ...            ...           ...             ...
2026-02-13         6.9012        90.6400       1181.35          213.34
2026-02-16         6.8844        90.6537       1182.95             NaN
2026-02-17         6.8852        90.6850       1183.30             NaN
2026-02-18         6.8867        90.6788       1185.77             NaN
NaT                   NaN            NaN           NaN             NaN

            CTTWBUSA Index
2000-03-01        102.1843
2000-03-02        102.0699
2000-03-03        102.0664
2000-03-06        102.0657
2000-03-07        102.0595
...                    ...
2026-02-13        103.3611
2026-02-16        103.1725
2026-02-17        103.2271
2026-02-18        103.2615
NaT                    NaN

[6777 rows x 17 columns]